---
title: "Geography 176A"
author: "[Leslie Alonzo](https://LeslieAlonzo98.github.io)"
subtitle: 'Daily Exercise 17'
output:
  html_document:
    theme: journal
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(sf)
library(stars)
library(units)
library(raster)
library(mapview)
library(elevatr)
library(rmapshaper)
library(USAboundaries)
library(rgdal)
library(osmdata)
library(leaflet)
```

```{r, echo = FALSE, warning=FALSE, message=FALSE}
gol = read_csv("../docs/uscities.csv") %>% 
  st_as_sf(coords = c("lng","lat"), crs = 4326) %>% 
  filter(city == "Goleta") %>%
  dplyr::select(city) %>% 
  st_transform(5070) %>%
  st_buffer(5000) %>% 
  st_bbox() %>% 
  st_as_sfc() %>%
  st_as_sf()

elev = elevatr::get_elev_raster(gol, z = 11) %>% 
  crop(gol)

log10(elev)


elev2 = elev
elev2[elev2 <= 0] = NA

plot(elev2)

writeRaster(elev2, filename = "../../geog-176A-labs/data/goletaelev.tif", overwrite = TRUE)

```

```{r, echo = FALSE, warning=FALSE, message=FALSE}

#CALC 

FUN = function(x){ ifelse(x <= 0, NA, 1) }

elev3 = calc(elev, FUN)

mask = elev * elev3


#Reclassify


rcl = data.frame(min = seq(0, 500, 100), max = seq(100, 600, 100), lab = c(0:5))

rc = reclassify(mask, rcl, lowerTRUE=TRUE)

s = stack(elev, elev3, mask, rc) %>% 
  setNames(c("elevation", "land-mask", "terrain", "topography"))

plot(s, col = viridis::viridis(256))


```

```{r, echo = FALSE, warning=FALSE, message=FALSE}
gol84 = gol %>% 
  st_transform(4326)

osm = osmdata::opq(gol84) %>%
  add_osm_feature(key = 'amenity',
                  value = "restaurant",
                  key_exact = TRUE,
                  value_exact = TRUE,
                  match_case = TRUE,
                  bbox = NULL) %>% 
  osmdata_sf()

print(osm)

golres = osm$osm_points %>% 
  filter(!name %in% (NA)) %>% 
  dplyr::select(osm_id, name, amenity)

gre = function(elev3){ ifelse(elev3 <= 0, NA, 1) }

grelev = calc(elev3, gre)

golreselev = elevatr::get_elev_raster(grelev, z = 11)

finalelev = elev3 * golreselev

golresleaf <- leaflet() %>%
  addProviderTiles(providers$Stamen.Watercolor) %>%
  addMarkers(data = golres, popup = ~name, label = ~name)
  
golresleaf


```

